name: flutter_number_trivia
description: Reso Coder TDD tutorial.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  data_connection_checker_nulls: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
flutter:
  uses-material-design: true
